version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing Docker...
      - docker --version

  pre_build:
    commands:
      - echo Logging in to GitHub Container Registry...
      - echo $github_token | docker login ghcr.io -u main --password-stdin

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ghcr.io/hngkhermn/laravel-app:latest .

  post_build:
    commands:
      - echo Pushing the Docker image to GHCR...
      - docker push ghcr.io/hngkhermn/laravel-app:latest

artifacts:
  files: []
