name: Laravel Docker Image CI - GHCR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      
      - name: Install Composer and Dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-interaction --prefer-dist

      - name: Copy .env.example to .env
        run: |
          cp .env.example .env
          echo "DB_HOST=db-server" >> .env
          echo "DB_DATABASE=db_laravel" >> .env
          echo "DB_PASSWORD=232425" >> .env

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ghcr.io/hngkhermn/multiple-app:latest
